### ISSUE TITLE
I need to remove Guava 31.1.1 jar file dependency.

### ISSUE THREAD

**Issue by sundramtrivedi** [GoogleCloudPlatform/getting-started-java#1236]
I have created Ant project in Eclipse. I have run code without guava file it give me this error. I don't want to use guava file.
Please me out for in this issue.

Jan 15, 2024 1:32:21 PM org.openqa.selenium.remote.service.DriverService$Builder getLogOutput
INFO: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/io/ByteStreams
	at org.openqa.selenium.remote.service.DriverService$Builder.getLogOutput(DriverService.java:471)
	at org.openqa.selenium.edge.EdgeDriverService$Builder.createDriverService(EdgeDriverService.java:352)
	at org.openqa.selenium.edge.EdgeDriverService$Builder.createDriverService(EdgeDriverService.java:147)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:507)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:47)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:43)
	at kb.testedge.main(testedge.java:10)
Caused by: java.lang.ClassNotFoundException: com.google.common.io.ByteStreams
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 7 more

**Comment by minherz** [comment]
Hello @sundramtrivedi, I am not an expert in Eclipse and I'm afraid we don't provide Eclipse specific support.
I can try to help you but I will need more details about the problem in question.
What code sample from this repo are you trying to run/use?
Please note that [guava](https://github.com/google/guava) is an integral part of many code samples. Taking it out means you modify the sample. Under the published [license](https://github.com/GoogleCloudPlatform/getting-started-java/blob/main/LICENSE) you can modify and use any code from this repo as you please as long as you follow the license agreement and the modified code behavior is your sole responsibility.
You are welcome to submit the version of the code sample that works without guava package by following [contribution](https://github.com/GoogleCloudPlatform/getting-started-java/blob/main/CONTRIBUTING.md) guidelines. We will be glad to review it and to consider for adding it to the repo.

**Comment by sundramtrivedi** [comment]
Hi,
I am using selenium 4.16 and it's give me this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet
	at org.openqa.selenium.remote.ErrorCodes.\<clinit>(ErrorCodes.java:104)
	at org.openqa.selenium.remote.ErrorHandler.\<init>(ErrorHandler.java:64)
	at org.openqa.selenium.remote.ErrorHandler.\<init>(ErrorHandler.java:55)
	at org.openqa.selenium.remote.RemoteWebDriver.\<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.chromium.ChromiumDriver.\<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.edge.EdgeDriver.\<init>(EdgeDriver.java:61)
	at org.openqa.selenium.edge.EdgeDriver.\<init>(EdgeDriver.java:57)
	at org.openqa.selenium.edge.EdgeDriver.\<init>(EdgeDriver.java:49)
	at kb.testedge.main(testedge.java:21)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more

Please help me if you know about it.

**Comment by minherz** [comment]
Hello @sundramtrivedi I feel confused. Please help me understand the following:

* What code samples from this repository are you trying to run that throws this exception?
* What is a reason for you to remove a package that, judging by the exception, is an integral part of the code exectuion?

Please not that the provided exception stacktrace clearly points to the missing class `com.google.common.collect.ImmutableSet` which is provided by the guava package.

**Comment by sundramtrivedi** [comment]
I have develop a code to print pdf of a webpage so for this I have used selenium 4.10. In this used one jar file is guava31.1.1
For a some reason I need to delete this jar file. But my code is not working when I am running the code with guava31.1.1 jar file.
For removing this dependency, I want any substitute file of this or any code concept that I can used in my program.

This I comfortable with guava30.1.1 version but this code only run for upper version of this.

**Comment by digaobarbosa** [comment]
I have a suggestion for the team. Why not "shade", or remove entirely the dependency of non GCP libraries from the path.
I have been dealing with similar problems this week, where I used maven shade plugin to handle this.
But it really is a bad experience compared to the Java AWS SDK where you have very few dependencies that are not from AWS itself.

So many projects use Guava for example, that makes it hard for a library to publish a version with a dependency on it.
