### ISSUE TITLE
Spring boot apps not starting with spring-boot-starter-web:1.5.4.RELEASE

### ISSUE THREAD

**Issue by AlbertoImpl** [GoogleCloudPlatform/getting-started-java#257]
Downgrading to `1.5.3.RELEASE` works.

But with `spring-boot-starter-web:1.5.4.RELEASE`
Following the steps and running `mvn appengine:run` or  `,/mvnw appengine:run` raises this exception:
```
[INFO] GCLOUD: Caused by:
[INFO] GCLOUD: java.lang.NoSuchMethodException: org.springframework.boot.autoconfigure.web.HttpMessageConverters$$EnhancerBySpringCGLIB$$3ba87c15.<init>()
[INFO] GCLOUD: 	at java.lang.Class.getConstructor0(Class.java:3082)
[INFO] GCLOUD: 	at java.lang.Class.newInstance(Class.java:412)
[INFO] GCLOUD: 	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:73)
[INFO] GCLOUD: 	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:201)
[INFO] GCLOUD: 	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
[INFO] GCLOUD: 	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver.buildLazyResolutionProxy(ContextAnnotationAutowireCandidateResolver.java:100)
[INFO] GCLOUD: 	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver.getLazyResolutionProxyIfNecessary(ContextAnnotationAutowireCandidateResolver.java:45)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1063)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
[INFO] GCLOUD: 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1316)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1282)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1180)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1096)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:659)
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
[INFO] GCLOUD: 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
[INFO] GCLOUD: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
[INFO] GCLOUD: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
[INFO] GCLOUD: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
[INFO] GCLOUD: 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
[INFO] GCLOUD: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
[INFO] GCLOUD: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
[INFO] GCLOUD: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
[INFO] GCLOUD: 	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
[INFO] GCLOUD: 	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
[INFO] GCLOUD: 	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
[INFO] GCLOUD: 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
[INFO] GCLOUD: 	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
[INFO] GCLOUD: 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:330)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.start(Server.java:422)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.doStart(Server.java:389)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.jetty9.JettyContainerService.startContainer(JettyContainerService.java:346)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:271)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:219)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
[INFO] GCLOUD: 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:217)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:359)
[INFO] GCLOUD: 	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:223)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:214)
[INFO] GCLOUD: 2017-06-29 22:09:14.029:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@1e6308a9{HTTP/1.1,[http/1.1]}{localhost:8080}
[INFO] GCLOUD: 2017-06-29 22:09:14.046:INFO:oejs.Server:main: Started @3980ms
[INFO] GCLOUD: jun 29, 2017 10:09:14 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFORMACIÓN: Module instance default is running at http://localhost:8080/
[INFO] GCLOUD: jun 29, 2017 10:09:14 PM com.google.appengine.tools.development.AbstractModule startup
[INFO] GCLOUD: INFORMACIÓN: The admin console is running at http://localhost:8080/_ah/admin
[INFO] GCLOUD: jun 29, 2017 10:09:14 PM com.google.appengine.tools.development.DevAppServerImpl doStart
[INFO] GCLOUD: INFORMACIÓN: Dev App Server is now running
```
Any idea on what could be happening?

Thanks,
Alberto

**Comment by lesv** [comment]
Fixed.

**Comment by lesv** [comment]
Leaving open to remind me to generate some testing for this - so it doesn't auto update.

**Comment by AlbertoImpl** [comment]
Is there any way to make it work with `1.5.4.RELEASE`?

**Comment by lesv** [comment]
I'll look at that.

**Comment by captainjapeng** [comment]
I'm also unable to build the **kotlin-springboot-appengine-standard**

[Here's the log](https://github.com/GoogleCloudPlatform/getting-started-java/files/1184949/log.txt)

**Comment by lesv** [comment]
@jabubake says that 1.5.6.RELEASE works fine.

**Comment by lesv** [comment]
Important that you use the latest `gcloud` -- `gcloud components update`

**Comment by ravikancherla** [comment]
I am still getting this on 1.5.7.RELEASE

**Comment by lesv** [comment]
#306 should have fixed things.  If not, please reopen.
