### ISSUE TITLE
com.google.cloud.datastore.DatastoreException: no matching index found

### ISSUE THREAD

**Issue by Jearil** [GoogleCloudPlatform/getting-started-java#448]
When attempting to deploy or run locally the bookshelf-2 project, I receive the following error. There does not seem to be any documentation at https://cloud.google.com/java/getting-started/tutorial-app on setting up an index. The error also doesn't specify what index needs to be set up.

```
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] 
[INFO] GCLOUD: Application startup error:
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)
[INFO] GCLOUD: Caused by: com.google.datastore.v1.client.DatastoreException: no matching index found., code=FAILED_PRECONDITION
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:180)
[INFO] GCLOUD: 	... 51 more
[INFO] GCLOUD: 
[INFO] GCLOUD: org.eclipse.jetty.deploy.DeploymentManager: Unable to reach node goal: started
[INFO] GCLOUD: com.google.cloud.datastore.DatastoreException: no matching index found.
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:129)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:114)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:182)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:178)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:174)
[INFO] GCLOUD: 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:173)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:73)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:167)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:158)
[INFO] GCLOUD: 	at com.example.getstarted.util.DatastoreSessionFilter.init(DatastoreSessionFilter.java:85)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:136)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
[INFO] GCLOUD: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:510)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:153)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:172)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:65)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:145)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:598)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.start(Server.java:418)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1797)
[INFO] GCLOUD: 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)
[INFO] GCLOUD: Caused by: com.google.datastore.v1.client.DatastoreException: no matching index found., code=FAILED_PRECONDITION
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:180)
[INFO] GCLOUD: 	... 51 more
[INFO] GCLOUD: 
[INFO] GCLOUD: org.eclipse.jetty.server.session: nodeaef-default-20191106t100213-g6mv Stopped scavenging
[INFO] GCLOUD: org.eclipse.jetty.xml.XmlConfiguration: 
[INFO] GCLOUD: com.google.cloud.datastore.DatastoreException: no matching index found.
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:129)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:114)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:182)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:178)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:174)
[INFO] GCLOUD: 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:173)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:73)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:167)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:158)
[INFO] GCLOUD: 	at com.example.getstarted.util.DatastoreSessionFilter.init(DatastoreSessionFilter.java:85)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:136)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
[INFO] GCLOUD: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:510)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:153)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:172)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:65)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:145)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:598)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.start(Server.java:418)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1797)
[INFO] GCLOUD: 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)
[INFO] GCLOUD: Caused by: com.google.datastore.v1.client.DatastoreException: no matching index found., code=FAILED_PRECONDITION
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:180)
[INFO] GCLOUD: 	... 51 more
[INFO] GCLOUD: 
[INFO] GCLOUD: Exception in thread "main" com.google.cloud.datastore.DatastoreException: no matching index found.
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:129)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:114)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:182)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:178)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:174)
[INFO] GCLOUD: 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
[INFO] GCLOUD: 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:173)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:73)
[INFO] GCLOUD: 	at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:57)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:167)
[INFO] GCLOUD: 	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:158)
[INFO] GCLOUD: 	at com.example.getstarted.util.DatastoreSessionFilter.init(DatastoreSessionFilter.java:85)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:136)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
[INFO] GCLOUD: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
[INFO] GCLOUD: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:854)
[INFO] GCLOUD: 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
[INFO] GCLOUD: 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:510)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:153)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:172)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:430)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:65)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:145)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:598)
[INFO] GCLOUD: 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.start(Server.java:418)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
[INFO] GCLOUD: 	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
[INFO] GCLOUD: 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1797)
[INFO] GCLOUD: 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] GCLOUD: 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1746)
[INFO] GCLOUD: Caused by: com.google.datastore.v1.client.DatastoreException: no matching index found., code=FAILED_PRECONDITION
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
[INFO] GCLOUD: 	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119)
[INFO] GCLOUD: 	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:180)
[INFO] GCLOUD: 	... 51 more
```

**Comment by Jearil** [comment]
Apparently the project must be using DataStore mode, not FireStore mode. This option can't be changed after selected and isn't specified in any of the documentation. Recommend the documentation be updated.
